### ISSUE TITLE
problem with getting ssm parameters

### ISSUE THREAD

**Issue by tnimni** [totango/helm-ssm#1]
Hi,

I'm getting this message:
postgreSqlPassword: {{ ssm /dev/sql/password us-east-1 }}): error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"ssm /dev/sql/password us-east-1":interface {}(nil)}

the file is like this

nameSpaces:
  infraNameSpaceName: 'ci-cd-infra'
  servicesNameSpaceName: 'ci-cd-services'

ciCdAirbnbService:
  secrets:
    postgreSqlPassword: {{ ssm /dev/sql/password us-east-1 }}

i ran the command aws ssm get-parameter --with-decryption --name /dev/sql/password --region us-east-1 | jq -r '.Parameter.Value'

and got the right value I don't understand what is the problem

using helm Client: &version.Version{SemVer:"v2.12.1", GitCommit:"02a47c7249b1fc6d8fd3b94e6b4babf9d818144e", GitTreeState:"clean"}

Can you please assist?

Thanks in advance

**Comment by tnimni** [comment]
i managed to debug the issue and i realized the password contained the & character that was causing the problem, but even after changing that it doesn't work

**Comment by amitlt** [comment]
@tnimni Hi tsachi, I tried replicated it and got it working.

I'm running `Client: &version.Version{SemVer:"v2.12.3", GitCommit:"eecf22f77df5f65c823aacd2dbd30ae6c65f186e", GitTreeState:"clean"}` fyi.

From what i could gather, there were two problems at play:

First of all, concerning the `&` character - Since the ssm script is written in bash, certain characters are problematic because of shell interpretation, the `&` character is one of them.

There are two levels of interpretation, one at the shell level, and one in the sed command level, which is used to replace the template with the value of the secret. Right now, there are two problematic characters that I know of, one is `&` and the other is `:` - these characters should be ignored in the values of the parameters. I'll consider rewriting the script in python to avoid these problems, but the initial intent fo this plugin is to provide a low requirement way of integrating ssm parameter into helm values.

Secondly, the issue where you saw that helm complains about the invalid map key seems to be because the {{ssm parameter/path region}} template was in the chart's default values, and when helm tried to read the default value file, encountered the template and couldnt convert it to json.
I'm not sure if the behaviour of reading the default value file is from a new helm version or not, I didnt encounter this behaviour because I didnt store a parameter in the default values file.

Regardless, the solution is to simply quote the parameter template like so:

```
ciCdAirbnbService:
    secrets:
        postgreSqlPassword: "{{ssm /dev/sql/password us-east-1}}"
```

I'll consider changing the template from two brackets ({{}}) to two square brackets ([[]]) to avoid this problem in the future, but that would invalidate current value files.

**Comment by amitlt** [comment]
@tnimni I provided a fix in [version 1.0.3](https://github.com/totango/helm-ssm/commit/91144c34c9ef6883f33de4787b01648dc653c42f)

You can now use `&` and `:` characters in parameters, as well as clearer documentation saying to quote the parameter template.

**Comment by tnimni** [comment]
Hi,
I have already solved the issue my self regarding the special chars,
Another issue was that I was expecting an ansible like behavior and it doesn't work like this here
I will open a pull request with my fix soon (I hope) it handles any special char so it's a general one

**Comment by amitlt** [comment]
Thanks a lot @tnimni .
Could you explain what do you mean by ansible-like behaviour?

**Comment by tnimni** [comment]
ansible perform the lookup function, on all file in the chat and template folders you don't need to input each and every file
thanks @amitlt
